### ISSUE TITLE
While trying to build a simple app and try to deploy had an error

### ISSUE THREAD

**Issue by AvanthaDS** [stackblitz/bolt.new#1201]
### Describe the bug

❯ npx vite build
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-30T20_27_07_391Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pkzfhn

### Steps to reproduce

Build the app and then press deploy 

while its building it gave the error 

### Expected behavior

Deploy as expected and show the result 

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = AvanthaDS
Chat ID = 1193ccb15e67
```

### Additional context

❯ npx vite build
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-30T20_27_07_391Z-debug-0.log

**Comment by kc0tlh** [comment]
@AvanthaDS Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for updates as we are investigating additional causes of this error there!

**Comment by AvanthaDS** [comment]
thanks alot.. this make sense ..
