### ISSUE TITLE
error prompt is too long: 203048 tokens > 200000 maximum

### ISSUE THREAD

**Issue by huyyy1** [stackblitz/bolt.new#1209]
### Describe the bug

egvery prompt i run gives me this error with bolt.new

whats happening

prompt is too long: 203037 tokens > 200000 maximum

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dufa4m

### Steps to reproduce

1. visit https://bolt.new/~/sb1-dufa4m
2. type any prompt

### Expected behavior

do something? not give me an error

### Screen Recording / Screenshot

https://www.loom.com/share/fca966d46239477489db7e2d1a9d761b

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 134313530,
  "usedJSHeapSize": 112068362,
  "jsHeapSizeLimit": 4294705152
}
Username = huyyy1
Chat ID = 186272f64805
```

### Additional context

wiith any prompt

prompt is too long: 203048 tokens > 200000 maximum

**Comment by kc0tlh** [comment]
@huyyy1 thanks for your report, and appreciate your patience as we are a small team working to support all of the new users! The context on this error, workaround ideas, and future updates on the R&D we are doing on this issue are being tracked in #1322 going forward so please go subscribe there!

**Comment by behnod24** [comment]
Hello Guys,

The issue appears to be with several files in the project. When the project becomes slightly more complex, the system displays this error. Hopefully, the Bolt team will resolve this issue soon.

Thank you

**Comment by houstongolden** [comment]
I am getting this same error now too. So frustrating. My project is not halted in bolt :(

**Comment by joaoguilhermels** [comment]
Same thing here. Just started testing bolt.

**Comment by taufec** [comment]
I just keep getting this error as soon as I subscribe to pro yesterday 😅

**Comment by osoull** [comment]
@taufec i'm in Pro and i'm blocked with this error :/

**Comment by taufec** [comment]
> @taufec i'm in Pro and i'm blocked with this error :/

The error seems gone after I use chrome. Ive use safari previously

**Comment by bigblackcoder** [comment]
ATTENTION: SOLVED!! Prompt is too long limitation bug

Well @stackblitz-gitops  @bolt
<img width="1495" alt="Screenshot 2024-11-17 at 10 30 40 PM" src="https://github.com/user-attachments/assets/a8c69922-dd8a-42ad-b6ec-6dcc177363fb">
<img width="1493" alt="Screenshot 2024-11-17 at 10 08 11 PM" src="https://github.com/user-attachments/assets/bc7d0fbe-8d57-41fd-acca-adac1b7f228d">
.new and my fellow Bolt builders, I've solved the issue of the the prompt too long bug for larger development projects. First, use the recommended https://30d61b3c.bolt-cnr.pages.dev/ URL. Now for me, when I went to the dev URL, none of my files were there! So i user my creative thinking and promlem solving skills.  So I copy my folder URL identifier for example: sb1-uz4pwq and put it together like this: https://30d61b3c.bolt-cnr.pages.dev/~/sb1-uz4pwx (not the real file but an example) And I got it get pass the bug and continue with my development pass the 200k token limit! (@stackblitz, you can hook me up with some incentives of my membership. Haha! ) FYI: You must used the dev URL your file number in order for it to work, otherwise you are going to be stuck like chuck!
