### ISSUE TITLE
Hello can you hear me is there anybody that can give me some means of direct communication so I can resolve redundant issues

### ISSUE THREAD

**Issue by wavemaker777** [stackblitz/bolt.new#1288]
### Describe the bug

I need someone to contact me so that I can resolve redundant issues regarding a site development that has been hampered by your platforms inability to respond and correct recovery

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-meju4m

### Steps to reproduce

'cause any of the buttons click on them they don't work scroll down they don't work I can't even get your editor to present formal versions of the site stored in my repository without their attempt to present some hybrid unfunctioning alternative

### Expected behavior

I expect the basic operations to function I also expect to be able to contact or communicate with somebody on your end I have tried for days your support links generate 404 hours I've left messages on your exit platform someone needs to contact me and assist me immediately or I will recreate this nightmare experience and advise any and all interested in developers to avoid this platform at all cost get in touch with me now

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 107353107,
  "usedJSHeapSize": 102995815,
  "jsHeapSizeLimit": 4294705152
}
Username = wavemaker777
Chat ID = 728d4fbd3edf
```

**Comment by witzulu** [comment]
> te development that has been hampered by your platforms inability to respond and correct recovery

This is an opensource project that people work on in there spare time it is very new. 

I doubt demanding help will work. if you are looking for a commercial active app maybe look at bolt.new this is a adaptation(fork) of that project. 

They will not allow you to use your own llm and you have to pay them directly. I prefer this project since it fits my usecase. but if you just want to complete app you can try them. Bolt.new is very stable right now. 

_**(this is just my opinion i am just as new as you but used to opensource github projects)**_

**Comment by kc0tlh** [comment]
@wavemaker777 customer support can be reached at hello@stackblitz.com
