### ISSUE TITLE
Word limit

### ISSUE THREAD

**Issue by shishen168** [stackblitz/bolt.new#1414]
The word limit completely affects the development. I hope the limit can be adjusted from 200,000 characters to 500,000. This will make the experience better. If the limit is only 200,000 characters, I recharged so many US dollars, and it feels like a waste of money

**Comment by endocytosis** [comment]
Hi @shishen168, 

We understand that these token context limits can be frustrating and are currently exploring optimizations to improve the efficiency of token usage. The issue is being tracked [here](https://github.com/stackblitz/bolt.new/issues/1322), which includes tips for improving token efficiency in your project.
