### ISSUE TITLE
CSS is not loading

### ISSUE THREAD

**Issue by FindMalek** [stackblitz/bolt.new#152]
### Describe the bug

![image](https://github.com/user-attachments/assets/dbcf9cfc-e7e3-42be-97d8-57efe0e76674)
CSS is not loading

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4hla38

### Steps to reproduce

yes

### Expected behavior

Supposed to have CSS

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/412b2e9b-e3c6-48de-8290-80383fd7d913)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71277414,
  "usedJSHeapSize": 69456466,
  "jsHeapSizeLimit": 2172649472
}
Username = FindMalek
Chat ID = 16dbfb18ffc9
```

**Comment by askadityapandey** [comment]
umm, the page is loading properly, can you specify more settings ?
![image](https://github.com/user-attachments/assets/a98fa939-24e9-47ef-a471-78a229c81979)

**Comment by samdenty** [comment]
We've just shipped a fix, the issue was we didn't have Full strict enabled on cloudflare and so some bots were accessing the bolt.new urls over non-secure https, causing cloudflare to cache a permanent redirect to the same url. Hopefully this should be fixed now, just clear your browsers network cache first - simply open devtools and check disable cache then reload then it should start loading. You can close devtools after that.
