### ISSUE TITLE
instructions bug

### ISSUE THREAD

**Issue by OmerAtayilmaz** [stackblitz/bolt.new#1607]
### Describe the bug

I said some stuff to prompt an action and explain the design, but then the AI just started explaining how to do it instead of actually making it.

### Link to the Bolt URL that caused the error

https://bolt.new/~/vitejs-vite-qarugm

### Steps to reproduce

just chat with ai, you'll see sometimes instead of action it just start to show how to do it.

### Expected behavior

taking action and creating files

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 88047014,
  "usedJSHeapSize": 81990974,
  "jsHeapSizeLimit": 4294705152
}
Username = OmerAtayilmaz
Chat ID = 04fb7b808192
```

### Additional context

I said some stuff to prompt an action and explain the design, but then the AI just started explaining how to do it instead of actually making it.

**Comment by endocytosis** [comment]
Hi @OmerAtayilmaz,

[Prompt engineering](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview) is a complex and interesting topic that is an area of active research. It is likely the LLM misunderstood your instructions and thus proceeded with an explanation rather than code generation. One possible solution is to start with a blank app template by clicking one of the icons on the bottom of the bolt.new homepage and then building from there. Additionally, using the prompt enhancement feature (click the sparkles icon at the bottom of the text input field after entering your prompt) can help.
