### ISSUE TITLE
Problem for paid users

### ISSUE THREAD

**Issue by noelemac01** [stackblitz/bolt.new#1623]
### Describe the bug

I just created an account, havent used it, paid the pro, and i cant prompt anything, it says ' You have hit the rate limit. Please Upgrade to keep chat' Can someone help with that?

### Link to the Bolt URL that caused the error

there is no URL

### Steps to reproduce

I have created the account
paid the pro version
wanted to prompt 
and then Error

### Expected behavior

Having good customer support option, to deal with paid customers

### Platform

windows, google chrome

### Additional context

.

**Comment by kc0tlh** [comment]
@noelemac01 It appears that something has gotten broken/confused on our back end. I cannot see your user in the DB at all.

Please reach out to [hello@StackBlitz.com](mailto:hello@StackBlitz.com) so that we can escalate this to engineering to dig in and try to properly restore your paid account status for you!
