### ISSUE TITLE
Daily Rate Limit Issue Despite Available Purchased Tokens

### ISSUE THREAD

**Issue by inovatadb** [stackblitz/bolt.new#1674]
### Describe the bug

Hello,
I'm encountering an issue with my account where I'm being rate-limited despite having over 4.8 million purchased tokens remaining. While I understand I've reached the daily limit of 150,000 tokens, I have a significant balance of purchased tokens (4,822,254) that I should be able to use.
Could you please help clarify:

Why I'm unable to access my purchased tokens
How I can utilize my remaining token balance
Whether this is a technical issue that needs to be resolved

My current usage stats are:

Daily: 150,000/150,000
Monthly: 193,183/1,000,000
Purchased tokens remaining: 4,822,254

Thank you for your assistance.
Best regards
<img width="513" alt="1b" src="https://github.com/user-attachments/assets/dc83c70f-c277-4df9-9454-926556dda21c">
<img width="482" alt="2b" src="https://github.com/user-attachments/assets/fc8c353e-c485-4378-b05e-706bc53f98fc">

### Link to the Bolt URL that caused the error

bolt.new (my account)

### Steps to reproduce

Details from my account

### Expected behavior

Use all tokens

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@inovatadb It appears that you've upgraded, canceled, upgraded again, and had many failed charges, along with some successful charges on your account. The net result is that something has gotten broken/confused on our back end. 

Please reach out to hello@StackBlitz.com so that we can escalate this to engineering to dig in and try to properly restore your paid account status for you!
