### ISSUE TITLE
I spent 16,000,000 tokens and no errors resolved...

### ISSUE THREAD

**Issue by krischulz** [stackblitz/bolt.new#1703]
I filed two reports about this. Bolt won't fix there errors and I just spent 16,000,000 tokens trying to fix it,  no results and no more tokens. There has to be a better way...

**Comment by Trisfidel** [comment]
Same here.

**Comment by endocytosis** [comment]
Hi all, 

We appreciate your patience as our small team works through the incredible volume of feedback we have received since launch. In issue #678 we have collected many best practices on error resolution and prompting strategies for efficient token usage. Additionally, you can subscribe there for updates on the product level changes that we are making to increase the amount of work you can get done per million tokens.

**Comment by REBEL33Soul** [comment]
Same here.
