### ISSUE TITLE
Install package bug

### ISSUE THREAD

**Issue by mathieulglobetechnologie** [stackblitz/bolt.new#1704]
### Describe the bug

I can't install package, so i'm blocked

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dkxbtt

### Steps to reproduce

Just send the description of my system and it never successfully to install package. After Try to fix to. 

### Expected behavior

Don't get this bug

### Platform

```
Browser name = Safari
Full version = 18.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15
performance.memory = undefined
Username = mathieuleclerc
Chat ID = 765d03be4127
```

**Comment by mathieulglobetechnologie** [comment]
So I think I lost a lot of tokens just to try to fix it.

**Comment by kc0tlh** [comment]
@mathieulglobetechnologie Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!
