### ISSUE TITLE
Image visibility

### ISSUE THREAD

**Issue by mjohnsiii** [stackblitz/bolt.new#1730]
### Describe the bug

Images I attach are never visible. I have used a ton of credits trying to fix this issue. please help

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-4f3234

### Steps to reproduce

Attach an image
Prompt for the image to show on the landing page in the hero section

### Expected behavior

Show image that has been attached

### Screen Recording / Screenshot

![Screenshot 2024-11-07 101546](https://github.com/user-attachments/assets/612bc2f6-0efd-4860-a565-94e1d8b21c34)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 76180270,
  "usedJSHeapSize": 54266934,
  "jsHeapSizeLimit": 4294705152
}
Username = mjohnsiii
Chat ID = 5d1fb81dfbee
```

### Additional context

PLEASE HELP!

**Comment by endocytosis** [comment]
Hi @mjohnsiii, 

If you open your project in StackBlitz (in Bolt, click "Open in StackBlitz" in the top right-hand corner), you can upload your image to the file directory (drag and drop the image into the Explorer on the left-hand side of the screen, making sure the file path is correct) so that it is displayed. Alternatively, you can download the code generated by Bolt (click the "Download" button in the top right-hand corner) and provide a path the image locally to continue development.

**Comment by mjohnsiii** [comment]
I don't know what this means. Shouldn't I be able to upload an image and it show on the site? This works with the simplest of web template sites. Very disappointed in this functionality. Tell me step by step what I should do. I am not a developer.

**Comment by endocytosis** [comment]
This is a known issue that is being tracked: #1809.
