### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by chunggainchi** [stackblitz/bolt.new#1973]
### Describe the bug

Trying to upload the screens but takes forever and wont load. even tho the size is not too big

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2pmfxf

### Steps to reproduce

go to upload image, try to upload an image

### Expected behavior

image uploaded so bolt can actually build what i designed

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by chunggainchi** [comment]
![Screenshot 2024-11-11 at 10 45 49](https://github.com/user-attachments/assets/0a59d005-f510-4a5c-98c8-3d376609c6f3)

**Comment by endocytosis** [comment]
Appreciate the feedback! As performance of these models continues to improve, users often have more success prompting piece of by piece rather than all at once. In this case, you could prompt Bolt with each image step by step to allow for changes in this fashion. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of insights on using Bolt most effectively while maximizing token efficiency.
