### ISSUE TITLE
Not Deploying

### ISSUE THREAD

**Issue by Overcomer7** [stackblitz/bolt.new#2003]
### Describe the bug

I have been trying to deploy my application but it keeps giving the error 
"Failed building the project. Make sure the build command is correct and try again."

Repeated attempts have faild and cost me hugely in credits or tokens. What's the way out?

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v1idza

### Steps to reproduce

go to the project Wishop2
Click on deploy
This is when the error msg comes
![err3gthub](https://github.com/user-attachments/assets/815f85a0-1bb0-4b73-8685-4b09ba6bb8e3)

### Expected behavior

It should have deployed the app to  netlify as expected. Since I am a non-tech guy I cannot tell you much more..

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Chrome

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2019

**Comment by Overcomer7** [comment]
Hi Brian,
you marked this as completed but its still giving me the same error!
I need a solution asap as I am losing credits fast, and time is running
out.qd

I already suffered a loss because the project I first started with was
Buyer Intent and once it was built I decided to subscribe, but after I hit
the subscribe and completed the payment, that project had vanished. So I
lost all those credits!
And now this!

Kindly help me get the app deployed.


Regards,
Hemant D Thorat
*Special Situations Advisor*
*Fund-raising, Growth Capital, M&A*

Mobile - 9545450297
https://www.linkedin.com/in/hemantdthorat/
Strategy - Capital - Growth
<https://mailtrack.io/l/459b074993a641575c5dee6d42a5d54fc469e6b2?url=http%3A%2F%2Fhemantdthorat.com&u=9514589&signature=480aced4e015d9b2>

**Comment by endocytosis** [comment]
Hi @Overcomer7, 

Are you able to find your project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection? 

Regarding the build error, I closed the issue here as we are tracking that with #2019 (consolidating all of these issues in one place). The team is hard at work improving the stability and performance of Bolt. We appreciate your patience as improvements are made!
