### ISSUE TITLE
previous chat will not appear in bolt.new 

### ISSUE THREAD

**Issue by jenkshi** [stackblitz/bolt.new#2063]
### Describe the bug

I am making a app with bolt.new in my PC I login using github. But when I try to login to another PC I can't see any past chats or projects I made.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

click at sign in ----> chose login with github account -----> account accessed -----> past chats or project are not visible.

### Expected behavior

the website should show all my chats and projects regardless where I am accessing them from

### Platform

- windows 11
- chrome
- Version: [e.g. 91.1]

**Comment by Bazz0r** [comment]
I had the same issue, it appears chats do not persist between browser sessions, this was confirmed by a contributor in another issue posted. The fix for me was this.

1. Go to https://stackblitz.com/ and login with your bolt.new account or GitHub login.
2. Go to Collections on the left hand side and click Bolt Collection.
3. Open up the Bolt collection you had originally created on bolt.new, it should have the same chat/project name.
4. When it opens, on the top left hand side click "Open In Bolt.new | AI"
5. Your chat is now visible again in bolt.new

Hopefully browser persistence will be added soon, I thought I had lost several hours of work. Hope this helps.

**Comment by jenkshi** [comment]
Thanks for the help

**Comment by endocytosis** [comment]
Glad this worked! We are aware of this issue with chat persistence and are tracking it here: #39. We appreciate your patience as improvements continue to be made!
