### ISSUE TITLE
My conversations have disappeared

### ISSUE THREAD

**Issue by MoiSet** [stackblitz/bolt.new#2069]
### Describe the bug

None of my conversations are showing up. Just yesterday, I subscribed to the Pro plan.

### Link to the Bolt URL that caused the error

https://bolt.new/

### Steps to reproduce

Go to the conversation history section.
Observe that no conversations are visible.

### Expected behavior

All previous conversations should be displayed.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Bazz0r** [comment]
I had the same issue, it appears chats do not persist between browser sessions, this was confirmed by a contributor in another issue posted. The fix for me was this.

Go to https://stackblitz.com/ and login with your bolt.new account or GitHub login.
Go to Collections on the left hand side and click Bolt Collection.
Open up the Bolt collection you had originally created on bolt.new, it should have the same chat/project name.
When it opens, on the top left hand side click "Open In Bolt.new | AI"
Your chat is now visible again in bolt.new
Hopefully browser persistence will be added soon, I thought I had lost several hours of work. Hope this helps.

**Comment by endocytosis** [comment]
Hi all, 

You are correct regarding the workaround! The team is hard at work improving chat persistence. This issue is being tracked here: #39. We appreciate your patience as improvements continue to be made!
