### ISSUE TITLE
Chats disappear after cache removal

### ISSUE THREAD

**Issue by iggypcnfsky** [stackblitz/bolt.new#2074]
### Describe the bug

i've removed cache from google chrome, and my chats have disappeared

### Link to the Bolt URL that caused the error

..

### Steps to reproduce

1 - start a chat
2 - remove cache/cookies from chrome
3 - see if there are chat still stored or not

### Expected behavior

i expected my chats to be stored not in the cache locally on my machine, but on some database

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Bazz0r** [comment]
I had the same issue, it appears chats do not persist between browser sessions, this was confirmed by a contributor in another issue posted. The fix for me was this.

Go to https://stackblitz.com/ and login with your bolt.new account or GitHub login.
Go to Collections on the left hand side and click Bolt Collection.
Open up the Bolt collection you had originally created on bolt.new, it should have the same chat/project name.
When it opens, on the top left hand side click "Open In Bolt.new | AI"
Your chat is now visible again in bolt.new
Hopefully browser persistence will be added soon, I thought I had lost several hours of work. Hope this helps.

**Comment by endocytosis** [comment]
Yes, this is correct! We are aware of this issue with chat persistence. Temporary workarounds and updates can be found here: #39. (Go to [stackblitz.com](http://stackblitz.com/), login (same credentials as Bolt), click Collections on the left-hand side, click Bolt Collection). Appreciate your patience as improvements continue to be made.
