### ISSUE TITLE
Just says installing dependincies 

### ISSUE THREAD

**Issue by theaisannin** [stackblitz/bolt.new#2086]
### Describe the bug

all i get is this then i get a error due to this error ive ran out of credits 
<img width="431" alt="Screenshot 2024-11-12 at 11 42 00" src="https://github.com/user-attachments/assets/4b6c8a39-309c-4c4c-b5fa-829409d2c2a2">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-q4dkkd

### Steps to reproduce

I ask it to build something then when installing dependincies it just stays on that then get a error ask it to fix it does the same installs it again then i get a error 

### Expected behavior

Its my first time using it so im guessing after installing that it will all work 

### Screen Recording / Screenshot

<img width="431" alt="Screenshot 2024-11-12 at 11 42 00" src="https://github.com/user-attachments/assets/798c2715-77e6-4a7f-ba25-422c98d856b6">

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = theaisannin@gmail.com
Chat ID = b5e1f5bb241d
```

**Comment by theaisannin** [comment]
I want to upgrade but I first want to see it works before upgrading

**Comment by theaisannin** [comment]
<img width="511" alt="Screenshot 2024-11-12 at 11 46 09" src="https://github.com/user-attachments/assets/e4c9edc3-2e48-4c88-8411-ec653f6d3fa6">
this is the error then when i say fix it installs then then just get the same thing

**Comment by kc0tlh** [comment]
@theaisannin Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!
