### ISSUE TITLE
nom install fails pretty consistently

### ISSUE THREAD

**Issue by georgzoeller** [stackblitz/bolt.new#2134]
### Describe the bug

❯ npm install
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

Then bolt goes on trying to fix it by setting a package.json publishConfig to set a http url (ugh!!!!)

This happens for any astro app I do. I frequently see out of memory errors flare up and the project reloading (safari/new m4 MacBook with 16GB)

So far, I have been unable to create any useful app,

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-y2uhpj

### Steps to reproduce

Just create any astro project, make some edits, eventually nom install fails

### Expected behavior

it to work

### Platform

- OS: macOS
- Browser: Safari
- Version: current

### Additional context

<img width="675" alt="image" src="https://github.com/user-attachments/assets/5a3a035c-3f93-4212-9616-741f31fe6061">

**Comment by kc0tlh** [comment]
@georgzoeller Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for updates as we are investigating additional causes of this error there!
