### ISSUE TITLE
NPM install not working for astro site

### ISSUE THREAD

**Issue by VanColt** [stackblitz/bolt.new#2165]
### Describe the bug

NPM install query never completed successfully for the astro site that the bolt prepared.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-tvzh9k

### Steps to reproduce

Insert "npm install" on the terminal and probably the issue will reproduce

### Expected behavior

Expected npm to install the requirements and then npm run dev for the preview

### Platform

```
Browser name = Safari
Full version = 18.0
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
performance.memory = undefined
Username = VanColt
Chat ID = 9e4d024b1174
```

**Comment by kc0tlh** [comment]
@VanColt Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!
