### ISSUE TITLE
React project : https not supported

### ISSUE THREAD

**Issue by Maxime-Oriol** [stackblitz/bolt.new#2232]
### Describe the bug

After building a basic React project linked with Firebase database, I got this error message:
```
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"
```

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-6cccpq

### Steps to reproduce

1. Create new React project
2. Integrage Firebase database
3. Build projet

### Expected behavior

No error and project built

### Platform

```
Browser name = Safari
Full version = 18.0
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
performance.memory = undefined
Username = Mapeeks
Chat ID = 2c702c1bf803
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by kc0tlh** [comment]
@Maxime-Oriol Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for updates as we are investigating additional causes of this error there!
