### ISSUE TITLE
NPM Install returns an error

### ISSUE THREAD

**Issue by briesenpap** [stackblitz/bolt.new#2295]
### Describe the bug

npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-14T09_50_43_479Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-pv4ldy

### Steps to reproduce

try to deploy the project

after 5 minutes, the above error message is returned. "Fix problem" does not fix the problem

### Expected behavior

deployment successful

### Screen Recording / Screenshot

![Bildschirmfoto 2024-11-14 um 11 17 09](https://github.com/user-attachments/assets/1945afcc-998b-465b-b88d-90031c7659e7)

### Platform

```
Browser name = Safari
Full version = 18.0.1
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0.1 Safari/605.1.15
performance.memory = undefined
Username = briesenpap
Chat ID = e711d3d8d6a0
```

**Comment by kc0tlh** [comment]
@briesenpap Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for updates as we are investigating additional causes of this error there!
