### ISSUE TITLE
Npm install do not work

### ISSUE THREAD

**Issue by nyckosleducmanage** [stackblitz/bolt.new#2554]
### Describe the bug

Npm failed to install components

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uzg3dp

### Steps to reproduce

Just start a new project and in the workflow bolt try to npm install

### Expected behavior

Block to npm install
_1 / idealTree:project: sill idealTree buildDeps

### Platform

```
Browser name = Safari
Full version = 604.1
Major version = 604
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/130.0.6723.90 Mobile/15E148 Safari/604.1
performance.memory = undefined
Username = nyckosleducmanage
Chat ID = 1a6ea22101a8
```

**Comment by endocytosis** [comment]
Hi @nyckosleducmanage, 

Could you try opening your project in Chrome and see if that works? Bolt is most compatible with Chrome and Chromium browsers.

**Comment by nyckosleducmanage** [comment]
Hello @endocytosis,

Sorry for the mistake, I have test with Chrome and post on GitHub with my IPad ;)

**Comment by kc0tlh** [comment]
@nyckosleducmanage Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

Since this did not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!
