### ISSUE TITLE
It always deploys to a new netlify

### ISSUE THREAD

**Issue by shevilpanchal** [stackblitz/bolt.new#2566]
### Describe the bug

It always deploys to a new netlify

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-brvlcz

### Steps to reproduce

Just deploy

### Expected behavior

It should just deploy to domain I have connected to already

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82286979,
  "usedJSHeapSize": 75999043,
  "jsHeapSizeLimit": 2160066560
}
Username = shevilpanchal
Chat ID = 69353c774a5e
```

**Comment by endocytosis** [comment]
Appreciate the feedback! Currently, the project should continue to reflect changes to the temporary domain when you re-deploy. We are aware of the request to have continued updates to the site associated with the custom domain and are tracking the issue here: #49. In the meantime, you can download the project files by clicking the download button at the top-right of the page and manage deployment manually. Hope this helps!
