### ISSUE TITLE
can't get anything to actually work

### ISSUE THREAD

**Issue by AK-GTMConsulting** [stackblitz/bolt.new#2622]
### Describe the bug

every app I try to create is giving me either an npm error message or there is no preview - I paid for this service and I've used a chunk of my credits and nothing works.  I even tried a super simple prompt to say build me a button that says hello when you press it and I have nothing in the preview.  I've tried to have the code reviewed on other services to see what was wrong and nothing is fixing the error 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-mgirro

### Steps to reproduce

give the ai any prompt, wait for it to build and load and get nothing in the preview and an npm error message over and over.

### Expected behavior

give it a prompt and get an app to play with

### Platform

```
Browser name = Safari
Full version = 18.0
Major version = 18
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
performance.memory = undefined
Username = AK-GTMConsulting
Chat ID = 0c9817cedb30
```

**Comment by jwillz7667** [comment]
yeah dude this is just bullshit, I have the same problem and want my money back, why would they put a product out and charge people for it when it doesn't work

**Comment by chita40** [comment]
same here .. we are not getting single line of useful code but it shows all types of error ..I hope we are paying for getting diffrent kind of error messages .. i too need my money back  we can call it bolt.error

**Comment by kc0tlh** [comment]
@AK-GTMConsulting  Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for troubleshooting steps and updates as we are investigating additional causes of this error there!

@jwillz7667 @chita40 refunds are processed via support@stackblitz.com

**Comment by chita40** [comment]
I am using google chrome not other browser ...
