### ISSUE TITLE
4.5M for free user [150k per day x30 days] and 10M for pro plan? 10M itself is very low, can you increase this?

### ISSUE THREAD

**Issue by KingLeoJr** [stackblitz/bolt.new#274]
4.5M for free user [150k per day x30 days] and 10M for pro plan? 10M itself is very low, can you increase this?

**Comment by Nemikolh** [comment]
Hey @KingLeoJr!

Just to clarify, free users do not get 4.5M per month but 1M.

Regarding the fact that this is very low, we're looking into reducing tokens usage so that when you use bolt you need less token to get started.

We've just landed the ability to buy more tokens so this is another option.

**Comment by mohammeddyousuf** [comment]
option missing to buy more tokens.

**Comment by managetesting** [comment]
After a month, tokens are renewed, are not??

**Comment by Jakoobster** [comment]
You could just up the tokens given instead of trying to make it cost less just match us with a good amount to avoid the high costs
