### ISSUE TITLE
Failure to Login. Chat failed to load.

### ISSUE THREAD

**Issue by tobybeedell** [stackblitz/bolt.new#2826]
### Describe the bug

I was mid-building my new app in the chat when it said that an unexpected error occurred. It straight after a pop up message in the bottom right hand corner of the creen saying failure to load chat history. 

Upon trying to refresh the page, it asked me to login in again.

After logging in the chat history is unable to load. Essentially my project is lost. Fortunately, I downloaded a copy of the code base earlier today. So all is not lost when you release the feature to upload a project from github.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-qksoqt

### Steps to reproduce

As above

### Expected behavior

To be able to continue iterating on my app build.

### Platform

- OS: macOS 15.1 (24B83)
- Browser: Chrome
- Version 130.0.6723.117 (Official Build) (x86_64)

### Additional context

all info above

**Comment by endocytosis** [comment]
Sorry to hear this! You can look for your past project by going to [stackblitz.com](https://stackblitz.com), logging in (same credentials as Bolt), clicking Collections on the left-hand side of the page, and then opening Bolt Collection.

If you have a chat open in Bolt, you can go to Settings > Backups to revert to a prior chat state.

Since you have a backup of your code, you can open a project in StackBlitz, drag and drop your code into the StackBlitz file system, and then click the Open in Bolt button at the top left to continue working on your project. 

Appreciate your patience as improvements continue to be made!
