### ISSUE TITLE
I LOST EVERYTHING

### ISSUE THREAD

**Issue by nonistack** [stackblitz/bolt.new#495]
**Is your feature request related to a problem? Please describe:**

 It told me to clear the cache but when I did I LOST EVERYTHING. I only cleared the cache from the past hour yet even my previous work from DAYS ago was lost. Why isn't there a backup to save everything? It's not like if I clear my caches my Google docs disappear. Clearing the cache should not have cleared everything.

**Describe the solution you'd like:**

 Give me back everything I've lost or reimburse my tokens for the work I've lost.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by benspak** [comment]
Hi @nonistack it sounds like the team is using local storage rather than persisting the data. Likely as an effort to be more efficient on the frontend. That said, it is certainly not efficient when someone loses all of their work! 

For this, I would email eric@stackblitz.com or reachout on x.com/ericsimons40 surely this issue qualifies for a refund.

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50
