### ISSUE TITLE
Configuration not allowing DB connections to work

### ISSUE THREAD

**Issue by benspak** [stackblitz/bolt.new#589]
### Describe the bug

Configured the browser with exceptions as requested. POSTman cannot access the API endpoints. Works locally, but not via StackBlitz.

### Link to the Bolt URL that caused the error

Look it up

### Steps to reproduce

View all of my other tickets LMAO

### Expected behavior

The DB to connect via a connection string that works locally and via MongoDB Compass

### Platform

```
Browser name = Chrome
```

**Comment by kc0tlh** [comment]
@benspak direct DB connections to traditional SQL DBs and such are not currently supported due to limitations of running entirely in the browser.

Most users are finding success with Firebase for DB, so we made this tutorial: https://x.com/sulco/status/1850937685512478850

I recommend that approach for now!
