### ISSUE TITLE
 Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by krisgnyc** [stackblitz/bolt.new#628]
### Describe the bug

npx vite build
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-16T04_06_13_206Z-debug-0.log

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-miakao

### Steps to reproduce

not sure

### Expected behavior

crashed app

### Screen Recording / Screenshot

npx vite build
npm ERR! code ERR_INVALID_PROTOCOL
npm ERR! Protocol "https:" not supported. Expected "http:"

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-10-16T04_06_13_206Z-debug-0.log

### Platform

```
Browser name = Safari
Full version = 17.6
Major version = 17
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
performance.memory = undefined
Username = krignyc
Chat ID = d4adf296da93
```

### Additional context

Error:
```
An unknown error occured while running an action.
```

**Comment by shivangswain** [comment]
Same error - https://bolt.new/~/sb1-bc9svg

**Comment by everspader** [comment]
Same error happening for me with `nom run dev` - I think this is a Safari thing because I don't see this error on Chrome.

**Comment by kc0tlh** [comment]
@krisgnyc Bolt.new does not currently support Safari due to limitations in the browser that do not support WebContainers (the core technology that powers Bolt). We are adding a banner to indicate this soon, but in the meantime, please switch to Google Chrome or another Chromium based browser.

If this does not resolve your issue, please subscribe to #2021 for updates as we are investigating additional causes of this error there!
