### ISSUE TITLE
Not saving my latest changes

### ISSUE THREAD

**Issue by ranrahav** [stackblitz/bolt.new#646]
### Describe the bug

I have created several apps that the last session was not saved.
That's a real bummer as I work hard and get good results then I have to do it all over again.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-u5lba4

### Steps to reproduce

1. Create a project
2. work until tokens end

### Expected behavior

Save the latest progress 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by samdenty** [comment]
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50

**Comment by blackcid** [comment]
I'm not free user and it's happening now to me

**Comment by vin2095** [comment]
Same happened to my codes as well. I am paid user. 

I worked so hard to build an output and now its all gone.

**Comment by Asterisk4444** [comment]
Exact Same Happened to me and it shows the chat but its hoistory onle keeps the first 3 prompts and changes anything after that if you reload or rollback now it simply breaks and loses 90% of my project i ould like to cancel my subscription but its nearly impossible im thinking of just reporting them for false advertisement and shady business practices and cancel my card alltogether this company is LAZY AF

**Comment by Asterisk4444** [comment]
Bolt is a Joke compared to GPT at best it constantly breaks and the tokens are totally fake its so obvious at this point with hundreds of reddits and quora speaking in the same issues including fake token system. this service is a SCAM (Dont Buy Into It.)

**Comment by OluStayhired** [comment]
Guys, this issue is still happening and I am not on the free tier. It's extremely frustrating and I'm losing the will to live here as I'm losing hours of work trying to re-construct outputs. What's the current status to fixing this. 

PS. I tried stackBlitz for the latest version and the latest version was not available

**Comment by PaeyMoopy** [comment]
Yup this just happened to me. Saved my work on my laptop and shut it down, the total file size of the exported zip was 190kb, I had a couple more tweaks I wanted to make so I logged on a couple hours later, its now 92kb. 

Luckily I have it backed up, but I cant do any more tweaks with Bolt now because of this.. very unfortunate. 
Been a paid user for almost a year.. might cancel now.
