### ISSUE TITLE
When tweaking page content, surrounding content is deleted

### ISSUE THREAD

**Issue by alakaii** [stackblitz/bolt.new#80]
### Describe the bug

When making requests to change elements of a page, the builder will often remove content around it, even when asked not to

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-g4aswm

### Steps to reproduce

Ask to make a tweak to a page, 
page reloads
has error, has to fix
views site and tweak is implemented but surrounding content is gone

### Expected behavior

content is fixed leaving the rest in place and unchanged

### Screen Recording / Screenshot

s

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 133103575,
  "usedJSHeapSize": 118024299,
  "jsHeapSizeLimit": 4294705152
}
Username = alakaii
Chat ID = b33a26d2d264
```

### Additional context

happened a few times now, 
asked to tweak the awards section of a page, and it ended up getting rid of everything but the awards section. 
really frustrating, esp when (even as a precaution) asked the client to not delete content unless specifically asked to do so

**Comment by kirjavascript** [comment]
Hi! 👋 Thanks a lot for the report!

We will be improving the AI's abilities going forward and then hopefully it should make less mistakes.

We're tracking this issue internally and will let you know when we have a resolution. you posted ✨

**Comment by kc0tlh** [comment]
Thanks for the report! Here are some tips on avoiding this behavior:

Use Specific and Focused Prompts
When prompting the AI, be clear and specific. Direct the model to focus on certain files or functions rather than the entire codebase, which can improve token usage efficiency. This approach is not a magic fix, but anecdotally we've seen evidence that it helps. Some specific prompting strategies that other users have reported as helpful:

Mention Specific Code Segments or Classes: When possible, refer to specific divs, classes, or functions to guide Bolt to the exact place where you want the changes made. You can do this manually in chat or by highlighting the relevant code in your project and [using the "Ask Bolt" functionality](https://x.com/stackblitz/status/1846953280972509616).

Use the Prompt Enhancer function: The better the prompt, the higher quality of the output — bolt․new can help you improve your prompts automatically with the [prompt enhancement feature](https://x.com/sulco/status/1846922673739153580)!

Be Specific About What Should Remain Unchanged: Mention explicitly that no modifications should occur to other parts of the site.
